#Init Syslog-server service
---
- name: "{{ syslog_service_name }} service config on host"
  template:
    src: systemd/syslog.service.j2
    dest: "/etc/systemd/system/{{ syslog_service_name }}.service"
    backup: yes
  notify: "{{ syslog_service_name }} restart"
